### ISSUE TITLE
Want to add some elements to your readme

### ISSUE THREAD

**Issue by anshulsoni4** [abhinavkashyap061/abhinavkashyap061#1]

**Comment by aparna03dubey** [comment]
Please assign it to me. I can help with the styling of readme.md file.

**Comment by abhinavkashyap061** [comment]
Hey guys! If you want to make quality contributions to my projects, you can view them here:

- To Do List app https://github.com/abhinavkashyap061/todolist
- Blog app https://github.com/abhinavkashyap061/Dear-Diary

Happy Hacking 🚀
